bookle/urls.py
from django.urls import path
from django.conf.urls import url 
from django.urls import include
from bookle import views

app_name = 'bookle'

urlpatterns = [
    path('', views.home, name='home'),
    path('about-us/', views.about_us, name='about_us'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('past-puzzles/', views.past_puzzles, name='past_puzzles'),

    # Login and Sign Up
    path('login/', views.login, name='login'),
    path('log-out/', views.log_out, name='log_out'),
    path('sign-up/', views.sign_up, name='sign_up'),

    # Profile pages
    path('user/<str:username>/', views.profile, name='profile'),
    path('user/<str:username>/edit/', views.edit_account, name='edit_account'),
    
    # Puzzle pages
    path('puzzle/daily/', views.daily_puzzle, name='daily_puzzle'),
    path('puzzle/<str:date>/', views.puzzle, name='puzzle'),
    path('puzzle/daily/complete/', views.complete, name='complete'),
    path('puzzle/<str:date>/complete', views.complete, name='complete'),
    path('puzzle/daily/complete/discussion/', views.discussion, name='discussion'),
    
    # Views used for AJAX
    path('suggestions/', views.BookSuggestions.as_view(), name='suggestions'),
    path('check-guess/', views.CheckGuess.as_view(), name="check_guess"),
    path('display-guess/', views.DisplayGuess.as_view(), name="display_guess"),
    path('save-score/', views.SaveScore.as_view(), name="save_score"),
    path('get-book-data/', views.GetBookData.as_view(), name="get_book_data"),
]

group1a_wad_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from bookle import views

app_name = 'bookle'

urlpatterns = [
    path('', views.home, name='home'),
    path('bookle/', include('bookle.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

bookle/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver


class Book(models.Model):
    ISBN_MAX_LENGTH = 13

    isbn = models.CharField(max_length=ISBN_MAX_LENGTH, unique=True)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    genre = models.CharField(max_length=50)
    release_year = models.IntegerField(null=True)
    country = models.CharField(max_length=255)
    cover = models.CharField(max_length=300, default='')
    description = models.TextField(max_length=1000, blank=True, null=True)

    def __str__(self):
        return self.isbn
    

class Puzzle(models.Model):
    puzzleID = models.IntegerField(unique=True, primary_key=True)

    date = models.DateField(unique=True)
    isbn = models.OneToOneField(Book, on_delete=models.CASCADE)
    difficulty = models.FloatField(null=True)
    popularity = models.FloatField(null=True)

    def __str__(self):
        return str(self.date)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    user_picture = models.ImageField(upload_to='profile_images', blank=True, default='profile_images/default.png')
    bio = models.CharField(blank=True, max_length=250)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()
        

class Score(models.Model):
    RATING_CHOICES = [(i, i) for i in range(1, 6)]

    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    guesses = models.IntegerField(null=True)
    success = models.BooleanField(default=False)
    difficulty = models.IntegerField(choices=RATING_CHOICES, null=True)
    popularity = models.IntegerField(choices=RATING_CHOICES, null=True)
    puzzleID = models.ForeignKey(Puzzle, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.guesses)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['userID', 'puzzleID'], name='unique_score')
        ]
    

class Comment(models.Model):
    commentID = models.AutoField(unique=True, primary_key=True)
    puzzleID = models.ForeignKey(Puzzle, on_delete=models.CASCADE)
    comment = models.CharField(max_length=300)
    userID = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

    

bookle/forms.py
from django import forms 
from django.contrib.auth.models import User
from bookle.models import Score, UserProfile
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth.forms import UserCreationForm
from django import forms
from bookle.models import Comment

# Is this used anywhere?
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
    
class ProfileEditForm(forms.ModelForm):
    bio = forms.CharField(required=False)
    user_picture = forms.ImageField(required=False)
    
    class Meta:
        model = UserProfile
        fields = ('bio', 'user_picture')

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    bio = forms.CharField(required=False)
    user_picture = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'user_picture')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            validate_email(email)
        except ValidationError:
            self.add_error('email', "Invalid email format.")

        if User.objects.filter(email=email).exists():
            self.add_error('email', "Email already in use.")

        return email

    def clean_user_picture(self):
        user_picture = self.cleaned_data.get('user_picture')
        return user_picture

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()
        return user

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.puzzle = kwargs.pop('puzzle', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        comment = super().save(commit=False)
        comment.userID = self.user
        comment.puzzleID = self.puzzle
        if commit:
            comment.save()
        return comment
    
class ScoreForm(forms.ModelForm):
    difficulty = forms.ChoiceField(choices=[(i, i) for i in range(1, 6)])
    popularity = forms.ChoiceField(choices=[(i, i) for i in range(1, 6)])

    class Meta:
        model = Score
        fields = ('difficulty', 'popularity')

    """def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.puzzle = kwargs.pop('puzzle', None)
        super().__init__(*args, **kwargs)"""

    """def save(self, commit=True):
        score = super().save(commit=False)
        score.userID = self.user
        score.puzzleID = self.puzzle
        if commit:
            score.save()
        return score"""

bookle/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth import logout as auth_logout
from django.urls import reverse
from django.contrib.auth.models import User
from bookle.models import Score
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from bookle.models import Comment
from bookle.forms import CommentForm, ScoreForm
from bookle.models import Puzzle, Score
from bookle.forms import RegisterForm, ProfileEditForm
from bookle.models import Score, Book, Puzzle, UserProfile
from django.views.generic import View
from bookle.helpers import get_book_names, get_guess_data, check_guess, get_target_book_data
from datetime import date, datetime
import json


def home(request):
    context_dict = {}
    return render(request, 'bookle/home.html', context = context_dict)

def about_us(request):
    context_dict = {}
    return render(request, 'bookle/about_us.html', context = context_dict)

@login_required
def leaderboard(request):
    puzzle = Puzzle.objects.filter(date=date.today())[0]
    todays_scores = Score.objects.filter(puzzleID=puzzle)
    todays_scores.exclude(guesses__isnull=True)
    leaderboard_data = todays_scores.order_by('guesses')[:5]
    context = {'leaderboard_guesses': leaderboard_data}
    return render(request, 'bookle/leaderboard.html', context)

def login(request):
    context_dict = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                auth_login(request, user)
                return redirect(reverse('bookle:home'))
            else:
                return HttpResponse("Your Bookle account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            context_dict['error_message'] = "Invalid login details supplied."
    return render(request, 'bookle/login.html', context_dict)
    
@login_required
def log_out(request):
    auth_logout(request)
    return redirect('bookle:home')

def sign_up(request):
    context_dict = {}
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            if User.objects.filter(username=username).exists():
                return render(request, 'bookle/sign_up.html', {'form': form, 'error': 'Username already exists'})
            user = form.save()
            # Authenticate the user
            user = authenticate(username=user.username, password=form.cleaned_data.get('password1'))
            # Log the user in
            auth_login(request, user)
            return redirect('bookle:home')
        else:
            context_dict['error'] = "Sign up failed"
    else:
        form = RegisterForm()
    context_dict['form'] = form
    return render(request, 'bookle/sign_up.html', context=context_dict)

@login_required
def profile(request, username=None):
    user = get_object_or_404(User, username=username)
    user_profile = UserProfile.objects.filter(user=user)[0]
    context_dict = {'user':user, 'userProfile':user_profile}
    return render(request, 'bookle/profile.html', context=context_dict)

@login_required
def edit_account(request, username):
    if request.user.username == username:
        user = get_object_or_404(User, username=username)
        if request.method == 'POST':
            form = ProfileEditForm(request.POST, request.FILES, instance=user.userprofile)
            if form.is_valid() and request.user.username == username:
                form.save()
                messages.success(request, 'Your profile was successfully updated!')
                return redirect('bookle:profile', username=user.username)
        else:  # This is the GET request handler
            form = ProfileEditForm(instance=user.userprofile)
            return render(request, 'bookle/edit_account.html', {'form': form, 'user': user})
    else:
        return render(request, 'bookle/home.html', {})

@login_required
def discussion(request, puzzle_date="daily"):
    context_dict = {}

    if puzzle_date == "daily":
        puzzle_date = str(date.today())

    context_dict['puzzleDate'] = puzzle_date
    puzzle = get_object_or_404(Puzzle, date=puzzle_date)
    has_rated = False
    if not Score.objects.filter(userID=request.user, puzzleID=puzzle).exists():
        return redirect('bookle:daily_puzzle')

    s = Score.objects.get(userID=request.user, puzzleID=puzzle)
    has_rated = True if ((s.difficulty != None) or (s.popularity != None)) else False
    
    comment_form = CommentForm(user=request.user, puzzle=puzzle)
    rating_form = ScoreForm(instance=s)

    if request.method == 'POST':
        if 'submit_comment' in request.POST:
            comment_form = CommentForm(request.POST, user=request.user, puzzle=puzzle)
            if comment_form.is_valid():
                comment_form.save()
                comment_form = CommentForm(user=request.user, puzzle=puzzle)
                
        elif 'submit_rating' in request.POST:
            rating_form = ScoreForm(request.POST, instance=s)
            if rating_form.is_valid() and not has_rated:
                rating_form.save()
                return redirect('bookle:discussion')

    comments = Comment.objects.filter(puzzleID=puzzle).order_by('-commentID')

    context = {
        'puzzle': puzzle,
        'comments': comments,
        'comment_form': comment_form,
        'rating_form': rating_form,
        'has_rated': has_rated,
    }

    return render(request, 'bookle/discussion.html', context)

def daily_puzzle(request):
    if not Puzzle.objects.filter(date=date.today()):
        puzzleCount = len(Puzzle.objects.all())
        p = Puzzle.objects.create(puzzleID=puzzleCount+1, date=date.today(), isbn=Book.objects.all()[puzzleCount])
    else:
        p = Puzzle.objects.get(date=date.today())
        
    today = str(p.date)

    context_dict = {'puzzleDate':today}
    if request.user.is_authenticated:
        if Score.objects.filter(userID=request.user, puzzleID=p).exists():
            return complete(request, date=today)
        
    return render(request, 'bookle/daily_puzzle.html', context=context_dict)

def puzzle(request, date=None):
    context_dict = {}
    
    try:
        puzzle_date = datetime.strptime(date, '%Y-%m-%d').date()
        context_dict['puzzleDate'] = str(puzzle_date)
    except:
        return redirect('bookle:home')
    
    p = get_object_or_404(Puzzle, date=puzzle_date)

    if request.user.is_authenticated:
        if Score.objects.filter(userID=request.user, puzzleID=p).exists():
            return complete(request, date=date)
    
    return render(request, 'bookle/daily_puzzle.html', context=context_dict)

def past_puzzles(request):

    pop_list = Puzzle.objects.order_by('-popularity')[:6]
    diff_list = Puzzle.objects.order_by('-difficulty')[:6]
    for p in pop_list:
        p.dateurl = str(p.date) 
    for p in diff_list:
        p.dateurl = str(p.date)   
    context_dict = {}
    context_dict['popular'] = pop_list
    context_dict['difficult'] = diff_list
    return render(request, 'bookle/past_puzzles.html', context=context_dict)

def complete(request, date="daily"):
    context_dict = {}
    return render(request, 'bookle/complete.html', context=context_dict)

class BookSuggestions(View):
    def get(self, request):
        if 'guess' in request.GET:
            guess = request.GET['guess']
        else:
            guess = ''
        
        books = get_book_names(max_results=5, starts_with=guess)
              
        return render(request, 'bookle/suggestions.html', {'books': books})

class DisplayGuess(View):
    def get(self, request):
        guess = request.GET.get('guess','')
        date = request.GET.get('date', '0000-0-0')

        context_dict = get_guess_data(guess, date)        

        return render(request, 'bookle/guess.html', context_dict)
        
class CheckGuess(View):
    def get(self, request):
        context_dict = {}
        
        guess = request.GET.get('guess','')
        date = request.GET.get('date', '0000-0-0')

        correct_guess, valid_guess = check_guess(guess, date)
        
        context_dict['correct_guess'] = (correct_guess)
        context_dict['valid_guess'] = (valid_guess)

        return HttpResponse(json.dumps(context_dict))
      
class SaveScore(View):
    def post(self, request):
        data = json.loads(request.body)
        guesses = data.get('count','')
        success = data.get('success', False)

        if User.objects.filter(username=data['user']):
            user = User.objects.get(username=data['user'])
            print("hey")
            if ('date' in data.keys()) and user.is_authenticated:
                puzzle_date = datetime.strptime(data['date'], '%Y-%m-%d').date()
                puzzle = Puzzle.objects.get(date=puzzle_date)

                s = Score.objects.get_or_create(userID=user, puzzleID=puzzle)[0]
                s.success = success

                if success:
                    s.guesses = guesses
                s.save()

        return redirect('bookle:complete')
    
class GetBookData(View):
    def get(self, request):
        context_dict = {}

        puzzle_date_str = request.GET.get('date', '0000-0-0')
        if puzzle_date_str == "daily":
            puzzle_date_str = str(date.today())
        
        puzzle_date = datetime.strptime(puzzle_date_str, '%Y-%m-%d').date()
        puzzle = Puzzle.objects.get(date=puzzle_date)

        context_dict = get_target_book_data(puzzle)

        if request.user.is_authenticated:
            s = Score.objects.get(userID=request.user, puzzleID=puzzle)
            context_dict['success'] = s.success

templates/bookle/about_us.html
{% extends 'bookle/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Us
{% endblock %}

{% block body_block %}
    <div class="container-fluid">
        <p id="black-headings">This site was made by...</p>
        <div class="about-us-main">
            <h4 class="group-1a">Sophie Lambie (2764964L)</h4>
            <p class="jobs">Worked on front end: HTML, CSS, URL structure, Leaderboard</p>
            <h4 class="group-1a">Rachel Horton (2733550H)</h4>
            <p class="jobs">Worked on: Database, Game Logic</p>
            <h4 class="group-1a">Adam Yuan (2736414Y)</h4>
            <p class="jobs">Worked on: Discussion Page, User Accounts</p>
            <h4 class="group-1a">Faraj Ahmed (2736261A)</h4>
            <p class="jobs">Worked on: Past Puzzles</p>
        </div>
    </div>
{% endblock %}

templates/bookle/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
    <head>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        {% block assets_block %}
        {% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static '/css/stylesheet.css' %}" />
        <title>
        Bookle - 
        {% block title_block %}
            Default Title 
        {% endblock %}
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>

    <body>
        <div id="menuBar">
            
            <a href="{% url 'bookle:daily_puzzle' %}"><img id="logo" src="{% static 'images/logo.png' %}" 
            alt="bookle logo"/></a>

            <a href="{% url 'bookle:home' %}"><img class="topIcons" src="{% static 'images/home.png' %}" 
            alt="link to home"/></a>
            {% if user.is_authenticated %}
                <a href="{% url 'bookle:log_out' %}"><img class="topIcons" src="{% static 'images/logout.png' %}"></a>
                <a href="{% url 'bookle:profile' user.username %}"><img class="topIcons" src="{% static 'images/user.png' %}"
                    alt="link to profile" /></a>
            {% else %}
                <a href="{% url 'bookle:login' %}"><img class="topIcons" src="{% static 'images/user.png' %}"
                alt="link to login" /></a>
            {% endif %}
            <a href="{% url 'bookle:leaderboard' %}"><img class="topIcons" src="{% static 'images/leaderboard.png' %}" 
            alt="link to leaderboard"/></a>
            <br>
        </div>

        <div>
            <br>
            {% block body_block %}
                This is body_block's default content
            {% endblock %}
        </div>

        <div id ="footer"> 
            <a href="{% url 'bookle:about_us' %}">Find out more about us</a>
        </div>
    </body>
</html>

templates/bookle/complete.html
{% extends 'bookle/base.html' %}
{% load staticfiles %}

{% block assets_block %}
    <script src="{% static 'scripts/complete.js' %}"></script>
{% endblock %}

{% block title_block %}
    Complete
{% endblock %}


{% block body_block %}
<div class="container-fluid">
    <h2 id="complete-title" ><strong>Congratulations! The Bookle answer was...</strong></h2>
    <div id="complete-guesses">
        <div id="complete-cover">
            <img id = "cover" src=""/>
        </div>

        &emsp; <strong>Title:</strong> <label id="title"></label> <br>
        &emsp; <strong>Author:</strong> <label id="author"></label><br>
        &emsp; <strong>Release Year:</strong> <label id="releaseYear"></label><br>
    </div>

    <div class="final-guess-count"></div>
    
    <div class="discussion-link">
        <h2>..Join the discussion with fellow players</h2>
       <a href="{% url 'bookle:discussion' %}"><strong><h2> here!</h2></strong></a>
    </div>
    <div class="past-puzzles-link">
        <h2>...Play past puzzles</h2>
        <a href="{% url 'bookle:past_puzzles' %}"><strong><h2> here!</h2></strong></a>
    </div>
</div>
{% endblock %}

templates/bookle/daily_puzzle.html
{% extends 'bookle/base.html' %}
{% load staticfiles %}

{% block assets_block %}
    <script src="{% static 'scripts/puzzle.js' %}" 
            defer
            data-puzzle-date="{{ puzzleDate }}"
            data-user="{{ user.username }}"></script>
{% endblock %}


{% block title_block %}
    Daily Puzzle
{% endblock %}


{% block body_block %}
    <div class="container-fluid">
        <div class ="guesses">
            <p id="validGuess"></p>
            <label id="text-surrounding-guess" for="guessInput">Your Guess: </label>
            <input name="inputBox" id="guessInput" type="text" list="list-suggestions" placeholder="Enter book here...">
            <button id="submitButton">Guess</button>
            &emsp; &emsp; 
            <label id="guess-count"></label>
        <div id="options"></div>
    </div>

    <div id="guessResults"></div>
</div>
{% endblock %}

templates/bookle/discussion.html
{% extends 'bookle/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Discussion
{% endblock %}

{% block body_block %}
<div class="container">
    <h2>Discussion</h2>
    <hr>
    {% for comment in comments %}
    <div class="comment-box">
        <div class="card-body">
            <h5 class="card-title">{{ comment.userID.username }}</h5>
            <p class="card-text">{{ comment.comment }}</p>
        </div>
    </div>
    {% empty %}
    <p>No comments yet.</p>
    {% endfor %}
    <hr>
    <div class="row">
        {% if not has_rated %}
        <div class="col-md-6">
            <h4>Rate this Puzzle</h4>
            <form method="post">
                {% csrf_token %}
                {{ rating_form.as_p }}
                <input type="hidden" name="puzzle_id" value="{{ puzzle.id }}">
                <button type="submit" name="submit_rating" class="btn btn-primary">Submit</button>
            </form>
        </div>
        {% endif %}
        <div class="col-md-6">
            <h4>New Comment</h4>
            <form method="post">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <input id="input-comment" type="hidden" name="puzzle_id" value="{{ puzzle.id }}">
                <button id="submit-comment" type="submit" name="submit_comment" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/bookle/edit_account.html
{% extends 'bookle/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Edit Account
{% endblock %}


{% block body_block %}
    <h1 id="edit-heading"> Edit {{ user.username }}'s Profile</h1>

    <div class="form-group">
    <form id="profile_form" method="post" action="{% url 'bookle:edit_account' username=user.username %}" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_bio" id="input-label"> Edit Bio:</label>
        <input type="text" name="bio" id="id_bio" class="form-control" value="" size="500" placeholder="Set bio here..." />
                <br />
        <label id="input-label" for="id_user_picture" id="input-label">Change User picture:</label>
        <input type="file" class="form-control-file form-control-sm" name="user_picture" accept="image/*" id="id_user_picture">
                <br />
        <button type="submit" class="btn btn-success">Save Changes</button>
    </div>
    </form>

{% endblock %}

templates/bookle/guess.html
{% load staticfiles %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static '/css/stylesheet.css' %}" />
</head>

<div class="container-fluid">
<div class="guessResultsCover">
    <br>
    <img id = "cover" src="{{ cover }}"/>
</div>

<div class="guessResultsCategories"> 
    <strong>Title:</strong> <label id="title">{{ title }}</label> <br>
    <strong>Author:</strong> <label class="{{ author_class }}" id="author">{{ author }}</label> <br>
    <strong>Release Year:</strong> <label class="{{ release_year_class }}" id="releaseYear">{{ release_year }}</label><br>
    <strong>Number of words in title:</strong> <label class="{{ no_of_words_class }}" id="noOfWords">{{ no_of_words }}</label><br>
</div>
</div>

templates/bookle/home.html
{% extends 'bookle/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Home Page
{% endblock %}


{% block body_block %}
    <div class="instructions">
        <h1>Welcome to Bookle!</h1>
        <p id="instructionsText"> To play the game, start entering the name of a novel then select it from the drop down menu. 
            If any of the details of your guessed novel match the answer, those details will go green. 
            If the release year is within the ten years of the answer or number of words in the title 
            is within 2 words of the answer, these will go orange - the arrows are there to help too! There 
            is a daily puzzle but you can also play the past most difficult and popular puzzles if one isn't 
            enough! </p>

        <h2 id="linkText">Play today's</h2> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
        <h2 id="linkText">Play past puzzles</h2>
        <br>
        <a href="{% url 'bookle:daily_puzzle' %}"><img class="logo-links" src="{% static 'images/logo.png' %}"/></a>
        &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
        <a href="{% url 'bookle:past_puzzles' %}"><img class="logo-links" src="{% static 'images/logo.png' %}"/></a>
        
    </div>
{% endblock %}

templates/bookle/profile.html
{% extends 'bookle/base.html' %}
{% load staticfiles %}
{% load static %}

{% block title_block %}
    Profile
{% endblock %}


{% block body_block %}
    {% if user %}
        <div class="profile-picture">
            <img id="pfp" src="{% get_media_prefix %}{{ userProfile.user_picture }}">
            &emsp; &emsp; &emsp; <h3 id="username">Welcome back, <strong>{{ user.username }}!</strong></h3><br />
        </div>

        <div>
            {% if userProfile.bio %}
                <p>Bio: {{ userProfile.bio }}</p></div>
            {% else %}
                <p>Bio: No bio yet!</p>
            {% endif %}
        </div>

        <div>
            <a href="{% url 'bookle:edit_account' userProfile.user.username %}"><button class="btn btn-success">Edit your account here!</button></a>
        </div>
    {% endif %}
{% endblock %}

templates/bookle/sign_up.html
{% extends 'bookle/base.html' %} 

{% block title_block %} Register {% endblock %}


{% block body_block %}
    <div class="float-container">
        <div class="login-child">
            <h2 id="login-green-headings">Sign Up Here!</h2>
            <form method="post" class="form-sign-up" role="form" action=".">
              {% csrf_token %}

                {% if form.errors %}
                    </br>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <p id="error-message">{{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                {% endif %}

                <br>
                <label for="id_username" id="input-label">Username:</label> 
                <input type="text" class="form-control" name="username" maxlength="150" autofocus="" required="" id="id_username">
                    
                <label for="id_email" id="input-label">Email:</label> 
                <input type="email" class="form-control" name="email" required="" id="id_email">

                <label for="id_password1" id="input-label">Password:</label>
                <input type="password" class="form-control" name="password1" required="" id="id_password1">

                <label for="id_password2" id="input-label">Password confirmation:</label> 
                <input type="password" class="form-control"name="password2" required="" id="id_password2"> <span class="helptext">Enter the same password as before, for verification.</span></p>
                <br />
                
                <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </div>

        <div class="signup-child">
            <h2 id="signup-green-headings">Already got an account?</h2>
            <p><a href="{% url 'bookle:login' %}">Login</a> to edit or view your existing account!</p>
        </div>
    </div>
{% endblock %}